- RFFT/Versions.toml
- RegisterMismatchCommon/Versions.toml
OK, trying to get things to pass via bumping the registry.
> Bump versions of RFFT and RegisterMismatchCommon

- TileTrees/Versions.toml
- TileTreesGUI/Versions.toml
@kdw503, did I do this correctly?
> Update TileTrees and TileTreesGUI

- README.md
This is easiest to review if you add `?w=1` to the URL (so that the diff ignores whitespace changes)
> Extensions and cleanups to README.md

- TileTrees/Deps.toml
- TileTrees/Package.toml
- TileTrees/Versions.toml
Repo: git@github.com:HolyLab/TileTrees.jl.git
Tree: 1875d436e92a7a9f9877bbcdb494e1ef21246d2c
> New version: TileTrees v0.2.0

- RegisterQD/Compat.toml
- RegisterQD/Deps.toml
- RegisterQD/Versions.toml
These should be the last step for fixing https://discourse.julialang.org/t/how-can-i-register-align-shifted-image-stacks/29244/32?u=tim.holy
> Tag new releases of RegisterQD

- TileTreesGUI/Compat.toml
- TileTreesGUI/Deps.toml
- TileTreesGUI/Versions.toml
UUID: f54becb8-3809-5a58-8f2d-748913078968
Repo:
Tree: 5c020eb8c5d66319871f1bc14ea229238806d5ff
CC @youdongguo
> New version: TileTreesGUI v0.1.2

- RegisterDeformation/Compat.toml
- RegisterDeformation/Versions.toml
UUID: c19381b7-cf49-59d7-881c-50dfbd227eaf
Repo:
Tree: e81a18563636607cbf8403d0070af1d4f1c32483
> New version: RegisterDeformation v0.3.4

- TileTrees/Versions.toml
Repo:
Tree: 52cb86589c08adaf79c73e76f785d6b1c6f523ee
> New version: TileTrees v0.3.1

- T/TileTreesGUI/Compat.toml
- T/TileTreesGUI/Package.toml
- T/TileTreesGUI/Versions.toml
UUID: f54becb8-3809-5a58-8f2d-748913078968
Repo:
Tree: c721e5bea525b3457c8cf1897937421fb7c4032d
> New version: TileTreesGUI v0.2.0

- F/FakeCells/Compat.toml
- F/FakeCells/Deps.toml
- F/FakeCells/Versions.toml
UUID: 597c7b4e-c0ec-11e8-1347-855d2b7c9c20
Repo:
Tree: fa82be24524ef88eead402ef2ce1f77092a8778f
> New version: FakeCells v0.2.0

- T/TileTrees/Compat.toml
- T/TileTrees/Versions.toml
Repo:
Tree: 424c98f4acda3a158507223778a0df31adf2ef65
> New version: TileTrees v0.3.3

- Q/QuadDIRECT/Compat.toml
- Q/QuadDIRECT/Package.toml
- Q/QuadDIRECT/Versions.toml
UUID: dae52e8d-d666-5120-a592-9e15c33b8d7a
Repo:
Tree: 4f2d28cfdc85401db5401037fb25d8891c376c37
> New version: QuadDIRECT v0.1.2

- I/ImagineInterface/Compat.toml
- I/ImagineInterface/Versions.toml
UUID: a9d8408c-0fb1-11e9-0067-cb067474114e
Repo:
Tree: 42eb3972389f63ab2666952b1d5a03e975287158
> New version: ImagineInterface v0.1.4

- R/RegisterDeformation/Compat.toml
- R/RegisterDeformation/Versions.toml
UUID: c19381b7-cf49-59d7-881c-50dfbd227eaf
Repo:
Tree: 2b26201263fa08bc6267fb20c781fe684e6904b7
> New version: RegisterDeformation v0.4.0

- R/RegisterQD/Compat.toml
- R/RegisterQD/Versions.toml
UUID: ac24ea0c-1830-11e9-18d4-81f172323054
Repo:
Tree: a5eb7df4e47770fe4481fe42d224465e890e0b2e
> New version: RegisterQD v0.2.3

- T/TileTrees/Versions.toml
Repo:
Tree: 9f23dd1375514559db78292442093ffc9573a38b
> New version: TileTrees v0.3.4

- F/FakeCells/Package.toml
- F/FakeCells/Versions.toml
UUID: 597c7b4e-c0ec-11e8-1347-855d2b7c9c20
Repo:
Tree: 9ca21fec4bfab6f484d285474661967694c75b3f
CC @youdongguo
> New version: FakeCells v0.2.1

- R/RegisterQD/Compat.toml
- R/RegisterQD/Versions.toml
UUID: ac24ea0c-1830-11e9-18d4-81f172323054
Repo:
Tree: 6b8259a11b81f832501d534953ea7cd454303914
> New version: RegisterQD v0.2.4

- R/RegisterMismatch/Compat.toml
- R/RegisterMismatch/Versions.toml
UUID: 3c0dd727-6833-5f5d-a1e8-c0d421935c74
Repo:
Tree: 2401c39997bb1f73e7fdf410ffd2d54c1553e96e
> New version: RegisterMismatch v0.3.1

- R/RegisterQD/Compat.toml
- R/RegisterQD/Versions.toml
UUID: ac24ea0c-1830-11e9-18d4-81f172323054
Repo:
Tree: 39dd1d60b0b34b71e74a3ad821ec6236f907b26a
> New version: RegisterQD v0.2.5

- R/RegisterDeformation/Compat.toml
- R/RegisterDeformation/Versions.toml
UUID: c19381b7-cf49-59d7-881c-50dfbd227eaf
Repo:
Tree: 7576278e5c5cb3fecfeee22d52519e6db0d0b7a1
> New version: RegisterDeformation v0.4.2

- R/RegisterMismatch/Compat.toml
- R/RegisterMismatch/Versions.toml
UUID: 3c0dd727-6833-5f5d-a1e8-c0d421935c74
Repo:
Tree: af8f1da9d443bfef44365dc447e4e920438c77cd
> New version: RegisterMismatch v0.3.3

- R/RegisterMismatchCommon/Compat.toml
- R/RegisterMismatchCommon/Versions.toml
UUID: abb2e897-52bf-5d28-a379-6ca321e3b878
Repo:
Tree: 18f1606581974de100f37d6088aa2b7d66f97ccb
> New version: RegisterMismatchCommon v0.2.3

- .github/workflows/TriggerTagBot.yml
> update PAT secret name in TriggerTagBot.yml

- R/RegisterDeformation/Compat.toml
- R/RegisterDeformation/Versions.toml
UUID: c19381b7-cf49-59d7-881c-50dfbd227eaf
Repo:
Tree: 7cadd339a63c448da9ed410917b308e72bc84bbc
@timholy merging this should trigger the TagBot I just updated on RegisterDeformation https://github.com/HolyLab/RegisterDeformation.jl/blob/master/.github/workflows/TagBot.yml
> New version: RegisterDeformation v0.4.3

- A/Autosampler/Compat.toml
- A/Autosampler/Package.toml
- A/Autosampler/Versions.toml
UUID: 0c2e7f7b-659f-4d17-98b1-b653e143444e
Repo:
Tree: feb09c360244d7563cf07a00d3d28db46591bcd9
> New version: Autosampler v0.1.2

- N/NeighborhoodClustering/Compat.toml
- N/NeighborhoodClustering/Deps.toml
- N/NeighborhoodClustering/Versions.toml
UUID: d32f3a2f-26fa-5ce0-a2ac-000c59351c13
Repo:
Tree: 5f080af827e28ae2bb88b94e5143efcc1d422538
> New version: NeighborhoodClustering v0.2.0

- N/NeighborhoodClustering/Versions.toml
UUID: d32f3a2f-26fa-5ce0-a2ac-000c59351c13
Repo:
Tree: 1d728bd4eaa0228a6408adaa0ae56b89f71f45d3
> New version: NeighborhoodClustering v0.2.1

- I/IntervalFastMath/Versions.toml
UUID: f385d984-c960-11e8-171c-977bba6b62a4
Repo:
Tree: 76e67d6c0005a749bfa9ea5e3013a103d5a52151
> New version: IntervalFastMath v0.2.1

- T/TileTrees/Compat.toml
- T/TileTrees/Versions.toml
Repo:
Tree: eb3b3f4c65eb7bbaa9fbff84e4324b0b8ec2aa24
> New version: TileTrees v0.3.5

- B/BoxTrees/Compat.toml
- B/BoxTrees/Deps.toml
- B/BoxTrees/Versions.toml
- M/MergePairwise/Compat.toml
- M/MergePairwise/Deps.toml
- M/MergePairwise/Versions.toml
- T/TileTreesGUI/Compat.toml
- T/TileTreesGUI/Versions.toml
These are the last of our packages holding back Images 0.25.
> Bump BoxTrees, MergePairwise, and TileTreesGUI

- R/RegisterMismatch/Compat.toml
- R/RegisterMismatch/Versions.toml
UUID: 3c0dd727-6833-5f5d-a1e8-c0d421935c74
Repo:
Tree: 0bbe3f4b124e8380eaac87f9789bac6f5ecc7e9f
> New version: RegisterMismatch v0.4.0

- R/RegisterPenalty/Compat.toml
- R/RegisterPenalty/Versions.toml
UUID: 464fa2a9-b19c-5c59-8698-f58c971f971e
Repo:
Tree: b0c516a8801f8d43687752597997afc4f359e25f
> New version: RegisterPenalty v0.3.0

- R/RegisterPenalty/Compat.toml
- R/RegisterPenalty/Versions.toml
UUID: 464fa2a9-b19c-5c59-8698-f58c971f971e
Repo:
Tree: 2c74cc75e08de93280f4e9ce9c72343ffcfc173b
> New version: RegisterPenalty v0.3.1

- R/RegisterFit/Compat.toml
- R/RegisterFit/Package.toml
- R/RegisterFit/Versions.toml
UUID: 36121b08-3789-5198-aff2-59a3443d9b59
Repo:
Tree: a511936ed98e29c5b90e5ef295dcbbacfe5f2b1c
> New version: RegisterFit v0.2.0

- Z/ZWarpedArrays/Compat.toml
- Z/ZWarpedArrays/Deps.toml
- Z/ZWarpedArrays/Versions.toml
UUID: 26d16474-33ca-11e9-0261-c59b979c6e18
Repo:
Tree: a34cdba2f65d9f24224912d511e544d135cf2a30
> New version: ZWarpedArrays v0.1.1

- R/RegisterOptimize/Compat.toml
- R/RegisterOptimize/Versions.toml
UUID: b981a1b5-4587-53b0-9c3d-454c648f6f8d
Repo:
Tree: b12cc1d49f7b49117087825c84d7c3e7721150be
> New version: RegisterOptimize v0.3.1

- R/RegisterOptimize/Versions.toml
UUID: b981a1b5-4587-53b0-9c3d-454c648f6f8d
Repo:
Tree: c2977575bd646930eb191a79ec5c95697f6f04a9
CC @ChantalJuntao
> New version: RegisterOptimize v0.3.2

- R/RegisterMismatchCuda/Compat.toml
- R/RegisterMismatchCuda/Deps.toml
- R/RegisterMismatchCuda/Versions.toml
UUID: ee0d8d85-fa18-576c-9601-66ebb12862d9
Repo:
Tree: 96b6f92499b287ad98a28f0bc203b11b0570ced9
> New version: RegisterMismatchCuda v0.3.2

- B/BoxTrees/Compat.toml
- B/BoxTrees/Versions.toml
UUID: 9cc36475-e10c-57f8-b33d-19dcb253ebc3
Repo:
Tree: a59170813f11344d8c6c571036514a8d377a095c
> New version: BoxTrees v0.0.4

- T/TiledFactorizations/Compat.toml
- T/TiledFactorizations/Versions.toml
UUID: 23bcbbb2-c0d4-11e8-38f2-37d4ddb111c4
Repo:
Tree: 74e7ada3582f5d29a3c7ce9e362ad9c5391fa9e5
> New version: TiledFactorizations v0.1.1

- README.md
> update to README due to changes in GitHub's ssh key requirements

- T/TileTrees/Compat.toml
- T/TileTrees/Deps.toml
- T/TileTrees/Versions.toml
Repo:
Tree: 9bac9c4cd2ba6526c395690ca5c9cf506686054e
> New version: TileTrees v0.3.6

- C/CellSegmentation/Compat.toml
- C/CellSegmentation/Deps.toml
- C/CellSegmentation/Package.toml
- C/CellSegmentation/Versions.toml
One slims dependencies, the other adds new features.
> Two new CellSegmentation versions

- T/TileTreesGUI/Compat.toml
- T/TileTreesGUI/Deps.toml
- T/TileTreesGUI/Versions.toml
UUID: f54becb8-3809-5a58-8f2d-748913078968
Repo:
Tree: 4acedf508187388bed3193d39dbf2cc4e866e61b
> New version: TileTreesGUI v0.3.0

- C/CenterIndexedArrays/Compat.toml
- C/CenterIndexedArrays/Versions.toml
UUID: 46a7138f-0d70-54e1-8ada-fb8296f91f24
Repo:
Tree: 8152c6b496605119c14e02ab51c78c6c192b2bc2
> New version: CenterIndexedArrays v0.2.2

- T/TileTrees/Versions.toml
Repo:
Tree: 7b4eb2686dac5912c126df9adc7e06272926efcb
> New version: TileTrees v0.3.7

- T/TileTrees/Versions.toml
Repo:
Tree: 93595c5b4c79972cedb74929acc0063350b9e0a5
> New version: TileTrees v0.3.8

- M/MergePairwise/Compat.toml
- M/MergePairwise/Deps.toml
- M/MergePairwise/Versions.toml
UUID: 2b713a72-c0d4-11e8-0e3e-e7c72182117a
Repo:
Tree: 73e24f82c407bd0e41a3a3e7d261aae828d4c3e2
> New version: MergePairwise v0.3.0

- C/CellSegmentation/Compat.toml
- C/CellSegmentation/Versions.toml
UUID: 304b7e5e-c0d4-11e8-1391-db3dfdb9ef20
Repo:
Tree: 178282268379adcd1664cad8d37c2d1cac37897d
> New version: CellSegmentation v0.2.3

- T/TileTreesGUI/Compat.toml
- T/TileTreesGUI/Deps.toml
- T/TileTreesGUI/Versions.toml
UUID: f54becb8-3809-5a58-8f2d-748913078968
Repo:
Tree: 32c668751a08a739eed4cab7ced2a409017f2a92
> New version: TileTreesGUI v0.4.0

- T/TileTrees/Deps.toml
- T/TileTrees/Versions.toml
Repo:
Tree: 8a23a8630e6a8661c1ceca794b7f8e9f05dfbe0a
> New version: TileTrees v0.3.9

- I/IntervalFastMath/Versions.toml
UUID: f385d984-c960-11e8-171c-977bba6b62a4
Repo:
Tree: 7abac88f23920791e47d5aaf9361854abdb7f810
> New version: IntervalFastMath v0.2.2

- I/ImagineInterface/Compat.toml
- I/ImagineInterface/Versions.toml
UUID: a9d8408c-0fb1-11e9-0067-cb067474114e
Repo:
Tree: 38c4ac81a30b71ee9a04337080740a404f9b88df
> New version: ImagineInterface v0.1.7

- I/ImaginePlots/Compat.toml
- I/ImaginePlots/Deps.toml
- I/ImaginePlots/Versions.toml
UUID: d076106b-79cb-5c5e-aa42-567a067496c5
Repo:
Tree: 4059dc073e5dc730dd70e90fead167b297c28c34
> New version: ImaginePlots v0.2.1

- T/TiledFactorizations/Compat.toml
- T/TiledFactorizations/Versions.toml
UUID: 23bcbbb2-c0d4-11e8-38f2-37d4ddb111c4
Repo:
Tree: 13d1d865e4958ad3395fda22ef9acea457d35e5e
> New version: TiledFactorizations v0.1.2

- I/IntervalFastMath/Versions.toml
UUID: f385d984-c960-11e8-171c-977bba6b62a4
Repo:
Tree: a306ed5f11cc26b72b72e665d06ab884b5df2b31
> New version: IntervalFastMath v0.3.0

- Registry.toml
- T/TaylorRemainders/Compat.toml
- T/TaylorRemainders/Deps.toml
- T/TaylorRemainders/Package.toml
- T/TaylorRemainders/Versions.toml
- T/TaylorRemainders/WeakDeps.toml
UUID: 395f9d9a-971b-4d1d-8fea-4857c99358f6
Repo: git@github.com:HolyLab/TaylorRemainders.jl.git
Tree: 94f543efd36659ed84bb3252dc02d28abc9277f7
> New package: TaylorRemainders v1.0.0

- I/IntervalFastMath/Versions.toml
UUID: f385d984-c960-11e8-171c-977bba6b62a4
Repo:
Tree: 6895f0367d65c5acdca74c2d31b83eb2b6a4d006
> New version: IntervalFastMath v0.3.1

- T/TaylorRemainders/Compat.toml
- T/TaylorRemainders/Versions.toml
UUID: 395f9d9a-971b-4d1d-8fea-4857c99358f6
Repo:
Tree: 1be723fd22119449f36168bd0f843528d207f47e
> New version: TaylorRemainders v1.0.1

- T/TaylorRemainders/Versions.toml
UUID: 395f9d9a-971b-4d1d-8fea-4857c99358f6
Repo:
Tree: b8e179b7a42bec35d657d442ff9f0f0f29c1c1dc
> New version: TaylorRemainders v1.0.2

- T/TaylorRemainders/Versions.toml
UUID: 395f9d9a-971b-4d1d-8fea-4857c99358f6
Repo:
Tree: e73122a170f859d76794c528532ff4924cd05fd2
> New version: TaylorRemainders v1.1.0

- R/RegisterQD/Compat.toml
- R/RegisterQD/Deps.toml
- R/RegisterQD/Versions.toml
UUID: ac24ea0c-1830-11e9-18d4-81f172323054
Repo:
Tree: bf74d7ddd3d103734e54c6c96fac265ab3d20f69
> New version: RegisterQD v0.3.2

- R/RegisterPenalty/Compat.toml
- R/RegisterPenalty/Versions.toml
UUID: 464fa2a9-b19c-5c59-8698-f58c971f971e
Repo:
Tree: 8c0ea32b693d66c442ca89a1c8f841c958ce2b30
> New version: RegisterPenalty v0.3.2

- R/RegisterFit/Compat.toml
- R/RegisterFit/Deps.toml
- R/RegisterFit/Versions.toml
UUID: 36121b08-3789-5198-aff2-59a3443d9b59
Repo:
Tree: a79df9f2a607606bbb2c616f1fa28ab4f3bca38d
> New version: RegisterFit v0.2.1

- M/MergePairwise/Versions.toml
UUID: 2b713a72-c0d4-11e8-0e3e-e7c72182117a
Repo:
Tree: 4fd934ea20347aa168e8eda644213d6120112774
> New version: MergePairwise v0.3.3

- T/TiledFactorizations/Compat.toml
- T/TiledFactorizations/Deps.toml
- T/TiledFactorizations/Versions.toml
UUID: 23bcbbb2-c0d4-11e8-38f2-37d4ddb111c4
Repo:
Tree: 5c170bb1370e77579fc9a83194099122710d407f
CC @youdongguo
> New version: TiledFactorizations v0.1.5

- C/CounterMarking/Compat.toml
- C/CounterMarking/Deps.toml
- C/CounterMarking/Package.toml
- C/CounterMarking/Versions.toml
- Registry.toml
> New package: CounterMarking v1.0.0
